version: '3'

tasks:
  build:
    desc: Build binary.
    cmds:
      - cmake . -B build/
      - cmake --build build/

  run:
    desc: Run binary.
    cmds:
      - ./build/tic-tac-toe

  debug:
      desc: Debug application.
      cmds:
        - lldb -o run ./build/tic-tac-toe

  clean:
    desc: Clean.
    cmds:
      - rm -Rf build/
