version: '3'

tasks:
  build:
    desc: Build binary.
    cmds:
      - cmake . -B build/
      - cmake --build build/

  run:
    desc: Run binary.
    cmds:
      - ./build/puissance4

  clean:
    desc: Clean.
    cmds:
      - rm -Rf build/
